[theme]
# Primary accent color for interactive elements.
# primaryColor = "#f20089"

# Background color for the main content area.
backgroundColor = "#CADCFC"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#8AB6F9"

# Color used for almost all text.
textColor = "#00246B"